# Generated by Django 5.1.1 on 2024-09-20 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("series_works_count", models.IntegerField(default=0)),
                ("primary_work_count", models.IntegerField(default=0)),
                ("numbered", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="author",
            old_name="bio",
            new_name="about",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="published_date",
        ),
        migrations.AddField(
            model_name="author",
            name="author_id",
            field=models.CharField(default="new", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="average_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="fans_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="gender",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="author",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="author",
            name="ratings_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="text_reviews_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="works_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="asin",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="books", to="books.author"),
        ),
        migrations.AddField(
            model_name="book",
            name="average_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="book_id",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="edition_information",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="format",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn13",
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="book",
            name="num_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="original_publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="book",
            name="rating_dist",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="ratings_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="series_position",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="book",
            name="text_reviews_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="work_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="BookList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("description_html", models.TextField(blank=True)),
                ("num_pages", models.IntegerField(default=0)),
                ("num_books", models.IntegerField(default=0)),
                ("num_voters", models.IntegerField(default=0)),
                ("created_date", models.DateField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("num_likes", models.IntegerField(default=0)),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                ("created_by_id", models.CharField(blank=True, max_length=100)),
                ("num_comments", models.IntegerField(default=0)),
                (
                    "books",
                    models.ManyToManyField(related_name="book_lists", to="books.book"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="books.series",
            ),
        ),
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
